//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N0817034_SoftEng2_Project.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=C:\\USERS\\JAMES\\SOURCE\\REPOS\\N0" +
            "817034-SOFTENG2-PROJECT\\N0817034-SOFTENG2-PROJECT\\WMSDATABASE.MDF;Integrated Sec" +
            "urity=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string C__USERS_JAMES_SOURCE_REPOS_N0817034_SOFTENG2_PROJECT_N0817034_SOFTENG2_PROJECT_WMSDATABASE_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_JAMES_SOURCE_REPOS_N0817034_SOFTENG2_PROJECT_N0817034_SOFTENG2_PROJECT_W" +
                    "MSDATABASE_MDFConnectionString"]));
            }
        }
    }
}
